In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],[1,225,1],[1,5,3]])

In [4]:
a.ndim

2

In [5]:
a.itemsize

4

In [6]:
a.dtype

dtype('int32')

In [7]:
a = np.array([[1,2,3],[1,225,1],[1,5,3]], dtype= np.float64)

In [8]:
a.dtype

dtype('float64')

In [9]:
a.itemsize

8

In [10]:
a

array([[  1.,   2.,   3.],
       [  1., 225.,   1.],
       [  1.,   5.,   3.]])

In [11]:
a.size

9

In [12]:
a.shape

(3, 3)

In [13]:
a = np.array([[1,2,3],[1,225,1],[1,5,3]],dtype = complex)

In [14]:
a

array([[  1.+0.j,   2.+0.j,   3.+0.j],
       [  1.+0.j, 225.+0.j,   1.+0.j],
       [  1.+0.j,   5.+0.j,   3.+0.j]])

In [15]:
np.zeros((6,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [16]:
np.ones((15,23))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1.,

In [17]:
#in python we have range 
l = range(10)

In [18]:
l

range(0, 10)

In [19]:
l[5]

5

In [20]:
#simalarlily we have in numpy 
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#for jump 2 between 2 words
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [23]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [24]:
a= np.array([[1,2],[1,5],[1,8]])

In [25]:
a

array([[1, 2],
       [1, 5],
       [1, 8]])

In [26]:
a.shape

(3, 2)

In [27]:
a.reshape(2,3)

array([[1, 2, 1],
       [5, 1, 8]])

In [28]:
#for flatten you array you use ravel function
a.ravel()

array([1, 2, 1, 5, 1, 8])

In [29]:
a

array([[1, 2],
       [1, 5],
       [1, 8]])

In [30]:
a.min()

1

In [31]:
a.max()

8

In [32]:
a.sum()

18

In [33]:
a.sum(axis =0)

array([ 3, 15])

In [34]:
a.sum (axis=1)

array([3, 6, 9])

In [35]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.        , 2.23606798],
       [1.        , 2.82842712]])

In [36]:
a

array([[1, 2],
       [1, 5],
       [1, 8]])

In [37]:
np.std(a)

2.6457513110645907

In [38]:
a

array([[1, 2],
       [1, 5],
       [1, 8]])

In [39]:
b= np.array([[14,2],[45,2],[1,3]])

In [40]:
b

array([[14,  2],
       [45,  2],
       [ 1,  3]])

In [41]:
a+b

array([[15,  4],
       [46,  7],
       [ 2, 11]])

In [42]:
a-b

array([[-13,   0],
       [-44,   3],
       [  0,   5]])

In [43]:
a/b

array([[0.07142857, 1.        ],
       [0.02222222, 2.5       ],
       [1.        , 2.66666667]])

In [44]:
a.dot(b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [45]:
c = np.array([6,7,8])

In [46]:
c

array([6, 7, 8])

In [47]:
c[0:2]

array([6, 7])

In [48]:
c[-1]

8

In [49]:
d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [50]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
d[1,2]

6

In [52]:
d[0:2,2]

array([3, 6])

In [53]:
b[:,1:2]

array([[2],
       [2],
       [3]])

In [54]:
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [55]:
for row in d:
    print(row)

[1 2 3]
[4 5 6]
[7 8 9]


In [56]:
for cell  in d.flat:
    print(cell)

1
2
3
4
5
6
7
8
9


In [57]:
np.vstack((a,d))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [58]:
a= np.arange(30).reshape(2,15)

In [59]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [61]:
reslut =np.hsplit(a,3)

In [62]:
reslut[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [64]:
reslut[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [65]:
reslut[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [66]:
a=np.arange(12).reshape(3,4)

In [67]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [68]:
b=a>4

In [69]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [70]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [71]:
a[b]=-1

In [72]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

In [75]:
g= np.arange(12).reshape(3,4)

In [76]:
g

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
for row in g:
    for cell in row:
        print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [82]:
for cell in g.flatten():
    print(cell)

0
1
2
3
4
5
6
7
8
9
10
11


In [87]:
for x in np.nditer(g,order='F'):
                   print(x)     #uses of nditer

0
4
8
1
5
9
2
6
10
3
7
11


In [89]:
for x in np.nditer(g,order='F',flags=['external_loop']):
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [93]:
for x in np.nditer(g,op_flags['readwrite']):
    x[...]=x*x

NameError: name 'op_flags' is not defined

In [94]:
b=np.arange(3,15,4).reshape(3,1)

In [95]:
b

array([[ 3],
       [ 7],
       [11]])

In [ ]:
for x,y in np.nditer